{application,weber,
             [{registered,[weber]},
              {description,"weber - is Elixir MVC web framework."},
              {vsn,"0.0.1"},
              {modules,['Elixir.Mix.Tasks.Run','Elixir.Mix.Tasks.Weber',
                        'Elixir.Weber.App','Elixir.Weber.Http.Url',
                        'Elixir.Weber.Route','Elixir.Weber.Supervisor',
                        'Elixir.Weber']},
              {applications,[kernel,stdlib,elixir]},
              {mod,{'Elixir.Weber',[]}}]}.